### ISSUE TITLE
Schematic Features Suggestion

### ISSUE THREAD

**Issue by ethsmith** [kangarko/Foundation#135]
Util features for Schematic Loading, Pasting, and Reading the contents of a schematic (what blocks are involved and what not) would be a really cool addition to Foundation.

1) How it would benefit others? Dealing with Schematics is a very popular thing for certain Server types, obviously we can use WorldEdit API as a dependency ourself but the API changes slightly between certain versions and Foundation is really good at making cross version compatibility.

2) What would happen if we won't implement this feature? How's your server being affected? Just takes longer to update and requires more, messy code to create cross version compatibility.

3) If suggesting something new - Can the old system be modified/improved instead? No

This is relatively low priority but I think it would be a cool Util.

**Comment by kangarko** [comment]
Thank you, that is an awesome suggestion! However since this is the first time I'm hearing this as a feature request, I'd politely decline and focus instead of features that are requested heavily.

However, we're open source, feel free to create a PR and I'll approve it if it's been tested and works properly :) I recommend creating a new class for this and putting it to the "model" package.
