### ISSUE TITLE
Foundation 6.3.4 : Method put(textures, com.mojang.authlib.properties.Property) Not Found

### ISSUE THREAD

**Issue by UltimateGamer200** [kangarko/Foundation#217]
Hello,

I noticed in the latest Foundation that head textures are having trouble loading and it's because it can't find a method in Mojang AuthLib. Is there any way this can be fixed so that head textures can load again? Error exception is attached here from one of my testers. Thanks!

[Exception](https://pastebin.com/adQd177F)

**Comment by ElroyKR** [comment]
Hello

Based on my investigation, the problem seems to be related to changes in the getMethod() method after a specific [commit](https://github.com/kangarko/Foundation/commit/19206f524f8827d84fe118b8a5608e33efbf336a).

In the previous code, this method only compared the method names. However, after the mentioned commit, it also compares the parameter types. The PropertyMap#put(K key, V value) method of AuthLib is a generic type, and it is changed to an "Object" type at runtime. As a result, the getMethod() method cannot find the method, leading to an error.

To resolve this issue, it may be necessary to modify the getMethod() method to handle Generic types as well.

**Comment by kangarko** [comment]
You can just make a pull request thank you

**Comment by kangarko** [comment]
Should be fixed in the latest pull request thanks to @CoobMC
