### ISSUE TITLE
Menu Button Evenement

### ISSUE THREAD

**Issue by maliimaloo** [kangarko/Foundation#230]
Good morning,

I take the liberty of submitting this issue because I noticed that having two identical buttons with the same description and item name does not always lead to the appropriate event related to each button. I suppose this is due to the reference based on the name or description of the item, which is why I suggest considering the possibility of using the item’s slot to assign the right button event, even if they are identical.

Thank you for your understanding.

**Comment by broken1arrow** [comment]
Yeah that something I warned him about for I think a year ago  So this is not a "bug" more how he implement the getItem logic.

**Comment by kangarko** [comment]
Thanks for submitting! I know but changing this to slot-based system introduced some other problems, I dont exactly remember which right now because as broken1arrow said it has been a long time.

I can try injecting NBT tags into the buttons so they are different. Leaving opened.

**Comment by broken1arrow** [comment]
> Thanks for submitting! I know but changing this to slot-based system introduced some other problems, I dont exactly remember which right now because as broken1arrow said it has been a long time.
> 
> I can try injecting NBT tags into the buttons so they are different. Leaving opened.

That approach I think will cost little, specially if you often update the buttons. At least I notes some lag, when you make button that either increase or decrease value and at the same time redraw all buttons (you notes the menu not respond and you can almost drag items from the menu after around 5 clicks). I have not test this with your menu api, only with my own and it use similar logic as yours. Don't know if it is the asynchronous saving to file mess it up or something else, if I only update the button you clicking on is it no issue at all and that menu have only 5 slots. 

What I did to solve it, I instead in getItemAt I take the button instance directly instead of item stack and bind the instance with a unique ID. You get the benefit you can also access other methods more easy in the button class and don't need the reflection = speed up your menu even more.

**Comment by maliimaloo** [comment]
Hey, I think it's a good solution with the NBT custom tag for really separate the different button.
Either way, you just have to find a solution to differentiate the buttons instead of just looking at the name of the item or the description :)

**Comment by broken1arrow** [comment]
> Hey, I think it's a good solution with the NBT custom tag for really separate the different button. Either way, you just have to find a solution to differentiate the buttons instead of just looking at the name of the item or the description :)

Currently he checks all meta on the item. I mean everything from display name to the set metadata. The NBT is one way to quick fix the problem, but will also decrease the performance specially if you update the button often. Like when you "animate" the buttons.

**Comment by kangarko** [comment]
@broken1arrow You can now use Position annotation over Button fields or override getSlot in the button anonymous class and this method will match each button uniquely.

**Comment by kangarko** [comment]
@maliimaloo done
