### ISSUE TITLE
[Suggestion] Ignore case sensitivity while checking required settings

### ISSUE THREAD

**Issue by v3Monsta** [kangarko/Foundation#31]
My suggestion isn't really a major feature or improvement to the library, it's more of a change to the library that liberates the developer using it to not force a specific naming style in the settings.yml.

It's great that you're teaching students proper programming practices and showing them how to write fast, readable code, however some things should be left up to the developer. My only real gripe is forcing people to use `Version: 1` instead of `version: 1`. Doesn't really seem like the library should limit the scheme to just pascal case.

I know this is ridiculous thing to worry over but I would like to see the checker in SimpleSettings ignore casing. Also, because this is a ridiculous thing it doesn't take precedence over other issues, but I would eventually like to see it added.

**Comment by kangarko** [comment]
I understand your point and reviewed the code. The problem lies in the library in Bukkit dealing with loading config values, that is case sensitive without the option to turning it off.

Adding a complicated workaround would mean we had to backport this into our library, which would add servicing, development and upgrades costs with every MC update (mainly lots of time) and crap ton of complexity.

So while I understand your points, a singular way of doing things is what we will stay faithful moving forward. However, have a look at the YamlStaticConfig and create your own Settings class directly like the original is, except those values being labeled differently. You then simply load it by calling YamlStaticConfig.load() method.

**Comment by v3Monsta** [comment]
Okay, thank you. I was not aware this is a bukkit limitation.
