### ISSUE TITLE
1.16.1: Enchants multiplying

### ISSUE THREAD

**Issue by Kiwinetic** [kangarko/Foundation#71]
I am following Project Orion and when I give myself an item with the enchant it applies it to the item multiple times. I am trying to get it to only apply it once like every enchant. I was told this is a foundation issue.

What I am getting (no errors): https://i.imgur.com/veBbQWw.png, the more times I give myself the sword, the more times the enchant will be on one of them: https://i.imgur.com/MQ9r7Gc.png

What I am supposed to get (picture is from the video): https://i.imgur.com/uSMJKq0.png

The enchant class: https://pastebin.com/hzWTHQfb
The command class that gives me the item: https://pastebin.com/EHcAP50b

**Comment by Magnum97** [comment]
What does the `BlackEnchant` class look like?

**Comment by Kiwinetic** [comment]
> What does the `BlackEnchant` class look like?

I linked it above, but here it is again: https://pastebin.com/hzWTHQfb

**Comment by Magnum97** [comment]
Sorry- I don't know why I had trouble clicking on that earlier.. anyway I have an idea but I am not that experienced with  SimpleEnchat, so I want to test it before I start spewing theories.

**Comment by Magnum97** [comment]
Well so much for my theory. What I did for testing is create blank plugin, copied your command and enchant class and run on fresh server. If I understand you correctly enchants would be increased / duplicated with each run of `/ce` command. I was not able to show that. I only got a single enchant after running it 20 times.

![2020-08-17_02 01 26](https://user-images.githubusercontent.com/39318657/90378011-b0a56180-e02d-11ea-9958-a0f9fa81d17f.png)

**Comment by ItzRozzaDev** [comment]
> Edit: I forgot to mention that I am using the latest version of Foundation, 5.6.2

You cannot be using Foundation 5.6.2 the latest version that works is 5.5.6 as  issue #69 is about that. Also this duplication glitch with enchants has been reported to me personally when the discord was open and I was helping out.

**Comment by Magnum97** [comment]
I'm not saying that your problem is not possible. I'm just reporting that on a server with zero other plugins, and Foundation 5.6.2 that I could not replicate the problem. Hopefully someone else is able to help you.
I have uploaded the code I used to test it to https://github.com/Magnum97/BlackEnchant.git All you need to do to compile is run `./gradlew shadowJar` or gradle.bat if on Windows. I included the jar as well for your convenience. In fact just prior to commenting I decided to compile with 5.5.6. Both are in that repo for you.

> You cannot be using Foundation 5.6.2

Please check #70 re: 5.6.2 and how to fix it. It did not occur to me until after posting that I should include my versions as you may not have the same. I also rolled back my Foundation to 5.5.6 but could not duplicate the glitch. You might try running it alone on a server to see if there is something else interfering with it.

**Comment by kangarko** [comment]
This was a known issue fixed in Foundation 5.6.3.
