### ISSUE TITLE
1.16.2: Plugins Using Foundation Break Recent Versions of Multiverse

### ISSUE THREAD

**Issue by Tolmikarc** [kangarko/Foundation#79]
Whenever I run a server with the most recent official release version of Multiverse-Core (version 4.1.0)  or the latest dev build (version 4.1.1) and a plugin that uses the Foundation Library (version 5.6.3) I am given a null pointer exception upon startup that causes Multiverse-Core to disable itself. Here is the error: https://pastebin.com/U2jw60Nu For my server, I have been using an old version of Multiverse-Core (2.5.0) but if a public resource uses the Foundation Library it would be impossible to ask everyone who downloads it to also download an old version. Thank you!

Tolmikarc

**Comment by kangarko** [comment]
Hi,

The cause of this problem is not in Foundation directly, however after we invoke ScriptEngine, Multiverse starts to act oddly since they did not implement this properly or Spigot has changed, or at least it seems like it.

Here are the same issues reported by others with potential solutions suggested as well:

https://github.com/Multiverse/Multiverse-Core/issues/2146
https://github.com/Multiverse/Multiverse-Core/issues/2131
